#!/usr/bin/env bash

set -xe;

export LADESA_DEPLOY_SETUP_CLUSTER=false;
export LADESA_DEPLOY_SETUP_CLUSTER_ENVIRONMENT=false;

export LADESA_DEPLOY_SERVICE_API_LOCAL=false;
export LADESA_DEPLOY_SERVICE_API_DEVELOPMENT=false;
export LADESA_DEPLOY_SERVICE_API_PRODUCTION=false;

export LADESA_DEPLOY_SERVICE_WEB_LOCAL=false;
export LADESA_DEPLOY_SERVICE_WEB_DEVELOPMENT=false;
export LADESA_DEPLOY_SERVICE_WEB_PRODUCTION=false;